apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s0bxrsn7q-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-59459620c5.dtjo.p3.openshiftapps.com/rhtap/rhtap-qe:75c9c993f2ee9ddbaab5599a958b0e889318fbad@sha256:49fbcefa29a6ea0b6a9e48a292a940b08e3a0bf4223216f9366bb4d17c834b44
          name: container-image
